//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GTScalp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ORDERS                      101
#define IDD_GTSCALP_DIALOG              102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_VUINDICIES                  105
#define IDD_VUOPTIONS                   106
#define IDD_VUSYMBOLSOFINTEREST         107
#define IDD_VUCHARTARMSINTRADAY         109
#define IDD_VUMARKETDEPTH               110
#define IDR_MAINFRAME                   128
#define IDD_VUKEYVALUES                 135
#define IDD_VUCHART                     136
#define IDC_TESTMESSAGE                 1003
#define IDC_GTSESSION1                  1004
#define IDC_BTNLOGIN                    1005
#define IDC_LOGOUT                      1006
#define IDC_BTNSTART                    1007
#define IDC_BTNTRADEFRAME               1012
#define IDC_ACCOUNTS                    1017
#define IDC_IQFEED                      1018
#define IDC_GTSESSION2                  1019
#define IDC_LBEXECADDR                  1020
#define IDC_LBEXECPORT                  1021
#define IDC_LBLVL2ADDR                  1022
#define IDC_LBLVL1ADDR                  1023
#define IDC_LBLVL1PORT                  1024
#define IDC_LBLVL2PORT                  1025
#define IDC_BTNPENDORD                  1029
#define IDC_ACCT1PENDORD                1030
#define IDC_ACCT2PENDORD                1031
#define IDC_KEYVALUES                   1032
#define IDC_BUTTON1                     1034
#define IDC_BTN_OPTIONS                 1034
#define IDC_BTNHISTORY                  1035
#define IDC_CHART                       1036
#define IDC_CHARTINDUARMS               1039
#define IDC_VUARMS                      1040
#define IDC_CHARTINDU                   1041
#define IDC_CHARTARMS                   1042
#define IDC_CHARTTICK                   1043
#define IDC_CHECK1                      1044
#define IDC_LIVE                        1044
#define IDC_DAYSAGO                     1045
#define IDC_ALLOWTRADES                 1046
#define IDC_COMBO2                      1049
#define IDC_SYMBOLLIST                  1049
#define IDC_MARKETDEPTHBID              1053
#define IDC_MARKETDEPTHASK              1054
#define IDC_BTNHFS                      1055
#define IDC_IQFEEDLOADSYMBOLS           1056
#define IDC_LOADDAILYDATA               1057
#define IDC_TESTHDF5                    1058
#define IDC_DNLDDAYSYMBOL               1059
#define IDC_IQCOMMANDLIST               1060
#define IDC_ENTRY1                      1061
#define IDC_IQFEEDCMD                   1062
#define IDC_DATETIMEPICKER2             1066
#define IDC_DATETIMEPICKER3             1067
#define IDC_ENDDAYCOUNT                 1069
#define IDC_ENDBARCOUNT                 1070
#define IDC_ENDDAYSELECT                1071
#define IDC_DATETIMEPICKER4             1072
#define IDC_DATETIMEPICKER5             1073
#define IDC_STATICRB                    1074
#define IDC_RBDARVAS                    1078
#define IDC_RBBOLLINGER                 1079
#define IDC_RBBREAKOUT                  1080
#define IDC_RADIO1                      1081
#define IDC_RADIO2                      1082
#define IDC_RADIO3                      1083
#define IDC_BTNSCAN                     1084
#define IDC_SCANTYPE                    1085
#define IDC_USEDAYSTART                 1086
#define IDC_USEDAYEND                   1087
#define IDC_OPENIB                      1088
#define IDC_IBACCT                      1089
#define IDC_IBWATCH                     1090
#define IDC_IBUNWATCH                   1091
#define IDC_IBCLOSE                     1092
#define IDC_GRPDATASOURCE               1093
#define IDC_DSIQFEED                    1094
#define IDC_DSIB                        1095
#define IDC_DSGT1                       1096
#define IDC_DSGT2                       1097
#define IDC_DS1                         1098
#define IDC_DSSIMULATION                1098
#define IDC_DS2                         1099
#define IDC_CHARTSYMBOL                 1100
#define IDC_RTCHART                     1101
#define IDC_BASKET                      1102
#define IDC_EDTFUNDS                    1103
#define IDC_BASKETPREPARE               1104
#define IDC_ADDTESTSYMBOLS              1105
#define IDC_GRPEXECUTION                1107
#define IDC_EXECIB                      1108
#define IDC_EXECGENESIS1                1109
#define IDC_EXECGENESIS2                1110
#define IDC_EXEC4                       1111
#define IDC_EXECSIMULATION              1111
#define IDC_EXEC5                       1112
#define IDC_CBOUTSIDERTH                1113
#define IDC_RBOSSELL                    1114
#define IDC_RBOSBUY                     1115
#define IDC_RBTTLMT                     1116
#define IDC_RBTTMKT                     1117
#define IDC_RBTTSTPLMIT                 1118
#define IDC_RBTTSTP                     1119
#define IDC_RBTT02                      1120
#define IDC_RBTT01                      1121
#define IDC_EBLIMITPRICE                1122
#define IDC_EBSTOPPRICE                 1123
#define IDC_GRPORDERSIDE                1124
#define IDC_GRPTRADETYPE                1125
#define IDC_BTNORDER                    1126
#define IDC_EDTPASSWORD                 1127
#define IDC_IQFWINDOWS                  1128
#define IDC_EDTORGSYMBOLNAME            1129
#define IDC_EDTALTSYMBOLNAME            1130
#define IDC_BTNSAVESYMBOL               1131
#define IDC_CLOSEBASKET                 1132
#define IDC_BTNSAVEBASKET               1133
#define IDC_BTNLOADBASKET               1134
#define IDC_BUTTON6                     1135
#define IDC_BTNSAFEBSKTDATA             1135
#define IDC_CBSIMULATOR                 1136
#define IDC_BTNSIMUASSIGNDIR            1137
#define IDC_BTNRUNSIM                   1138
#define IDC_BTNHDF5FLUSH                1139
#define IDC_BTNSTOPSIM                  1141
#define IDC_BUTTON2                     1143
#define IDC_BTNSKUNK                    1143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
